### PR TITLE
Add support for 'Tests' prefix and suffix

### PR DESCRIPTION
**Pull request by aleitamar**
pull request related to issue:
https://github.com/MoreUnit/org.moreunit.intellij.plugin/issues/8

### CODE REVIEW

**Comment by aleitamar** [comment]
I am getting the following error from the maven build:
"Server returned HTTP response code: 403 for URL: http://download-cf.jetbrains.com/idea/ideaIC-2016.3.tar.gz"

Any idea how to fix this?

**Comment by ndemengel** [comment]
Hi @aleitamar,

Thanks for your pull request! It looks like this version of IntelliJ isn't available anymore. I'll have a look a it (but not right now, sorry for that).

**Comment by aleitamar** [comment]
Thank you @ndemengel 

When would the updated plugin be available to download from Intellij?

**Comment by ndemengel** [comment]
I just submitted it. Awaiting an approval.

**Comment by ndemengel** [comment]
The new version has been approved, you can now upgrade the plugin.

**Pull request merged**
