### PR TITLE
Add support for test/spec/should in the suffix

### LINKED ISSUE #5: Support for using file extension to find test file
Thanks for the great plugin! Wondering if you would be open to a small PR that would add support for a test file that has the word "spec" or "test" as part of the file extension?  For example, many JS projects [suggest](https://angular.io/docs/ts/latest/guide/style-guide.html#!#02-10) having "spec" in the file name, such that `user.service.js` has a test file named `user.service.spec.js`.

### PR DESCRIPTION
**Pull request by jrust**
New capability that fixes #5:
- Allows for a test file to have the test information as part of the
  suffix. For example, a file named `someFile.js` could have a
  corresponding spec file named `someFile.spec.js`

### CODE REVIEW

**Comment by jrust** [comment]
It's unclear to me why the build is failing since it passes locally.  Any help appreciated 😦

**Comment by ndemengel** [comment]
Sorry for the late answer, I'm quite busy right now. I doubt you did anything wrong, rather I suspect that IntelliJ changed in some way and I should update the build script accordingly. It has been a journey to make it work the first time, I expect a lot a fun to fix it :-\

I will have a look at it this week-end.

**Comment by jrust** [comment]
Wondering if Java 6 support is still needed?  The [intellij article](https://intellij-support.jetbrains.com/hc/en-us/articles/206544909-IDE-doesn-t-start-after-updating-to-Mac-OS-Yosemite-or-Mavericks) indicates the information is obsolete and OSX 10.11 was the [last version](https://www.java.com/en/download/faq/java_6.xml) to support java 6.

**Comment by ndemengel** [comment]
I updated the configuration to use Java 8 and everything ran fine :-)

Unfortunately the script in charge of uploading the build result to https://plugins.jetbrains.com/plugin/7105 doesn't work anymore, due to some changes in Jetbrains Website. As soon as I figure out how to fix that, a new version will be published.

**Comment by ndemengel** [comment]
I finally managed to publish a new release. There are still some things to fix but hey, this is what happens when code sleeps during more than a year :-)

Thanks a lot for your work!

**Comment by jrust** [comment]
Great, thanks for the quick response!

**Pull request merged**
